export const LIST = "LIST_CONTACT";
export const LIST_SUCCESS = "LIST_CONTACT_SUCCESS";
export const LIST_FAILED = "LIST_CONTACT_FAILED";

export const CONFIRM = "CONFIRM_CONTACT";
export const CONFIRM_SUCCESS = "CONFIRM_CONTACT_SUCCESS";
export const CONFIRM_FAILED = "CONFIRM_CONTACT_FAILED";

export const RESET_DATA = "RESET_DATA_CONTACT";
export const RESET_DATA_ACTION = "RESET_DATA_ACTION_CONTACT";
