export const INFO = "INFO_METHOD_PAYMENT";
export const INFO_SUCCESS = "INFO_METHOD_PAYMENT_SUCCESS";
export const INFO_FAILED = "INFO_METHOD_PAYMENT_FAILED";

export const UPDATE = "UPDATE_METHOD_PAYMENT";
export const UPDATE_SUCCESS = "UPDATE_METHOD_PAYMENT_SUCCESS";
export const UPDATE_FAILED = "UPDATE_METHOD_PAYMENT_FAILED";

export const RESET_DATA = "RESET_DATA_METHOD_PAYMENT";
export const RESET_DATA_ACTION = "RESET_DATA_ACTION_METHOD_PAYMENT";
