export const LIST = "LIST_HISTORIES";
export const LIST_SUCCESS = "LIST_HISTORIES_SUCCESS";
export const LIST_FAILED = "LIST_HISTORIES_FAILED";

export const CANCEL = "CANCEL_HISTORIES";
export const CANCEL_SUCCESS = "CANCEL_HISTORIES_SUCCESS";
export const CANCEL_FAILED = "CANCEL_HISTORIES_FAILED";

export const CONFIRM = "CONFIRM_HISTORIES";
export const CONFIRM_SUCCESS = "CONFIRM_HISTORIES_SUCCESS";
export const CONFIRM_FAILED = "CONFIRM_HISTORIES_FAILED";

export const RESET_DATA = "RESET_DATA_HISTORIES";
export const RESET_DATA_ACTION = "RESET_DATA_ACTION_HISTORIES";
