export const ROUTES = {
  HOME_PAGE: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  // admin routes
  ADMIN_HOME_PAGE: "/admin",
  ADMIN_DASHBOARD: "/admin/dashboard",
  ADMIN_EMPLOYEE: "/admin/employee",
  ADMIN_CHANGEPASSWORD: "/admin/change_password",
  ADMIN_NEWS: "/admin/news",
  ADMIN_GUIRE: "/admin/guire",
  ADMIN_COIN: "/admin/coin",
  ADMIN_HISTORIES: "/admin/histories",
  ADMIN_HISTORIES_DETAIL: "/admin/histories/:id",
  ADMIN_HISTORIES_WITHDRAW: "/admin/histories_withdraw",
  ADMIN_HISTORIES_WITHDRAW_DETAIL: "/admin/histories_withdraw/:id",
  // ADMIN_HISTORIES_WITHDRAW: "/admin/histories_withdraw",
  ADMIN_CUSTOMER: "/admin/customer",
  ADMIN_CUSTOMER_DETAIL: "/admin/customer/detail",
  ADMIN_CONTACT: "/admin/contact",
  ADMIN_METHOD_PAYMENT: "/admin/method-payment",
};
