export const LIST = "LIST_EMPLOYEE";
export const LIST_SUCCESS = "LIST_EMPLOYEE_SUCCESS";
export const LIST_FAILED = "LIST_EMPLOYEE_FAILED";

export const ADD = "ADD_EMPLOYEE";
export const ADD_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_FAILED = "ADD_EMPLOYEE_FAILED";

export const EDIT = "EDIT_EMPLOYEE";
export const EDIT_SUCCESS = "EDIT_EMPLOYEE_SUCCESS";
export const EDIT_FAILED = "EDIT_EMPLOYEE_FAILED";

export const UPDATE = "UPDATE_EMPLOYEE";
export const UPDATE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_FAILED = "UPDATE_EMPLOYEE_FAILED";

export const DELETE = "DELETE_EMPLOYEE";
export const DELETE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_FAILED = "DELETE_EMPLOYEE_FAILED";

export const DETAIL = "DETAIL_EMPLOYEE";
export const DETAIL_SUCCESS = "DETAIL_EMPLOYEE_SUCCESS";
export const DETAIL_FAILED = "DETAIL_EMPLOYEE_FAILED";

export const CHANGE_ACTIVE = "CHANGE_ACTIVE_EMPLOYEE";
export const CHANGE_ACTIVE_SUCCESS = "CHANGE_ACTIVE_EMPLOYEE_SUCCESS";
export const CHANGE_ACTIVE_FAILED = "CHANGE_ACTIVE_EMPLOYEE_FAILED";

export const DOWNLOAD_EXCEL = "DOWNLOAD_EXCEL_EMPLOYEE";
export const DOWNLOAD_EXCEL_SUCCESS = "DOWNLOAD_EXCEL_EMPLOYEE_SUCCESS";
export const DOWNLOAD_EXCEL_FAILED = "DOWNLOAD_EXCEL_EMPLOYEE_FAILED";

export const RESET_DATA = "RESET_DATA_EMPLOYEE";
