export const LIST = "LIST_CUSTOMER";
export const LIST_SUCCESS = "LIST_CUSTOMER_SUCCESS";
export const LIST_FAILED = "LIST_CUSTOMER_FAILED";

export const ADD = "ADD_CUSTOMER";
export const ADD_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_FAILED = "ADD_CUSTOMER_FAILED";

export const EDIT = "EDIT_CUSTOMER";
export const EDIT_SUCCESS = "EDIT_CUSTOMER_SUCCESS";
export const EDIT_FAILED = "EDIT_CUSTOMER_FAILED";

export const UPDATE = "UPDATE_CUSTOMER";
export const UPDATE_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_FAILED = "UPDATE_CUSTOMER_FAILED";

export const DELETE = "DELETE_CUSTOMER";
export const DELETE_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_FAILED = "DELETE_CUSTOMER_FAILED";

export const DETAIL = "DETAIL_CUSTOMER";
export const DETAIL_SUCCESS = "DETAIL_CUSTOMER_SUCCESS";
export const DETAIL_FAILED = "DETAIL_CUSTOMER_FAILED";

export const RESET_DATA = "RESET_DATA_CUSTOMER";
